builders:
  flatc_builder:
    import: 'package:flat_buffers_generator/flat_buffers_generator.dart'
    builder_factories: ['flatcBuilder']
    build_extensions:
      '^schemas/{{}}.fbs': ['lib/schemas/{{}}.g.dart']
    auto_apply: dependents
    build_to: source
    defaults:
      options:
        input_dir: 'schemas'
        output_dir: 'lib/schemas'
        flatc_path: 'flatc'
